accounts.msg =(ciper)4d03e2d36840d8153c0201c32dec45949e8bab2911af9144ee1ed2298790dcc39c70679a3639c0add11d40420783efcff574ab61e19c7bfa2d8cf0d963e3bd3a2039ba4a6b27e7398f0613918adbce21
accounts.build-version=215

accounts.mailDetails.hostName=dev-accounts@eazybytes.com
accounts.mailDetails.port=9020
accounts.mailDetails.from=dev-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank Dev Environment

accounts.activeBranches[0]=Chennai
accounts.activeBranches[1]=Berlin
accounts.activeBranches[2]=Indianapollis
