accounts.msg =(cipher)120c82ffc9cf868c6e7608a36c0b55f0278fea17e3991ccb13397190f3b55c87205f72633b5e688730cfcafdbe364674fe1ede9ff45c0adb536ac8791e293b23671a2cd8e751b0a6fafbd6dd1deb255b
accounts.build-version=215

accounts.mailDetails.hostName=dev-accounts@eazybytes.com
accounts.mailDetails.port=9020
accounts.mailDetails.from=dev-accounts@eazybytes.com
accounts.mailDetails.subject=Your Account Details from Eazy Bank Dev Environment

accounts.activeBranches[0]=Chennai
accounts.activeBranches[1]=Berlin
accounts.activeBranches[2]=Indianapollis
