server:
  port : 2001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HarishNallaballe/HIS-FILES.git
          
           
management:
  security:
    enabled: false

  
    